# This is a basic workflow to help you get started with Actions

name: Maven Install

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but not for the master branch
  push:
    branches:
      - '*'
      - '!master'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #when repo is slow then it can take north of 10 minutes to validate
    timeout-minutes: 20
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # see https://github.com/actions/setup-java
      - name: Set up JDK 11 and .m2/settings.xml
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
      - name: Configure Git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      # see https://blog.frankel.ch/github-actions-maven-releases/
      - id: install
        name: maven install
        run: mvn --no-transfer-progress --batch-mode install
        