# This is a basic workflow to help you get started with Actions

name: Release and  Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # see https://github.com/actions/setup-java
      - name: Set up JDK 1.8 and .m2/settings.xml
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME # env variable for username in release:perform
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in release:perform
      # see https://gist.github.com/sualeh/ae78dc16123899d7942bc38baba5203c
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Configure Git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      # see https://blog.frankel.ch/github-actions-maven-releases/
      - id: release-prepare
        name: release prepare
        run: mvn --no-transfer-progress --batch-mode  "-Darguments=-Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}" release:prepare
      - id: release-perform
        name: release perform
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            release:perform
